//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Library.ApiResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiCore {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiCore() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Administracion.Library.ApiResources.ApiCore", typeof(ApiCore).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration/.
        /// </summary>
        public static string CreateAdministration {
            get {
                return ResourceManager.GetString("CreateAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista/.
        /// </summary>
        public static string CreateChecklist {
            get {
                return ResourceManager.GetString("CreateChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/.
        /// </summary>
        public static string CreateCity {
            get {
                return ResourceManager.GetString("CreateCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonData/.
        /// </summary>
        public static string CreateCommonData {
            get {
                return ResourceManager.GetString("CreateCommonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consorcio/.
        /// </summary>
        public static string CreateConsortium {
            get {
                return ResourceManager.GetString("CreateConsortium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsortiumSecure/.
        /// </summary>
        public static string CreateConsortiumSecure {
            get {
                return ResourceManager.GetString("CreateConsortiumSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad/.
        /// </summary>
        public static string CreateFunctionalUnit {
            get {
                return ResourceManager.GetString("CreateFunctionalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaboralUnion/.
        /// </summary>
        public static string CreateLaboralUnion {
            get {
                return ResourceManager.GetString("CreateLaboralUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager/.
        /// </summary>
        public static string CreateManager {
            get {
                return ResourceManager.GetString("CreateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message/.
        /// </summary>
        public static string CreateMessage {
            get {
                return ResourceManager.GetString("CreateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia/.
        /// </summary>
        public static string CreateMultimedia {
            get {
                return ResourceManager.GetString("CreateMultimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner/.
        /// </summary>
        public static string CreateOwner {
            get {
                return ResourceManager.GetString("CreateOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedad/.
        /// </summary>
        public static string CreateOwnership {
            get {
                return ResourceManager.GetString("CreateOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentType/.
        /// </summary>
        public static string CreatePaymentType {
            get {
                return ResourceManager.GetString("CreatePaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider/.
        /// </summary>
        public static string CreateProvider {
            get {
                return ResourceManager.GetString("CreateProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province/.
        /// </summary>
        public static string CreateProvince {
            get {
                return ResourceManager.GetString("CreateProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renter/.
        /// </summary>
        public static string CreateRenter {
            get {
                return ResourceManager.GetString("CreateRenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets/.
        /// </summary>
        public static string CreateTicket {
            get {
                return ResourceManager.GetString("CreateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users/.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker/.
        /// </summary>
        public static string CreateWorker {
            get {
                return ResourceManager.GetString("CreateWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration/{0}.
        /// </summary>
        public static string DeleteAdministration {
            get {
                return ResourceManager.GetString("DeleteAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista/{0}.
        /// </summary>
        public static string DeleteChecklist {
            get {
                return ResourceManager.GetString("DeleteChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/{0}.
        /// </summary>
        public static string DeleteCity {
            get {
                return ResourceManager.GetString("DeleteCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonData/{0}.
        /// </summary>
        public static string DeleteCommonData {
            get {
                return ResourceManager.GetString("DeleteCommonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consortium/{0}.
        /// </summary>
        public static string DeleteConsortium {
            get {
                return ResourceManager.GetString("DeleteConsortium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsortiumSecure/{0}.
        /// </summary>
        public static string DeleteConsortiumSecure {
            get {
                return ResourceManager.GetString("DeleteConsortiumSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit/{0}.
        /// </summary>
        public static string DeleteFunctionalUnit {
            get {
                return ResourceManager.GetString("DeleteFunctionalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaboralUnion/{0}.
        /// </summary>
        public static string DeleteLaboralUnion {
            get {
                return ResourceManager.GetString("DeleteLaboralUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager/{0}.
        /// </summary>
        public static string DeleteManager {
            get {
                return ResourceManager.GetString("DeleteManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message/{0}.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner/{0}.
        /// </summary>
        public static string DeleteOwner {
            get {
                return ResourceManager.GetString("DeleteOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedad/{0}.
        /// </summary>
        public static string DeleteOwnership {
            get {
                return ResourceManager.GetString("DeleteOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentType/{0}.
        /// </summary>
        public static string DeletePaymentType {
            get {
                return ResourceManager.GetString("DeletePaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider/{0}.
        /// </summary>
        public static string DeleteProvider {
            get {
                return ResourceManager.GetString("DeleteProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province/{0}.
        /// </summary>
        public static string DeleteProvince {
            get {
                return ResourceManager.GetString("DeleteProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renter/{0}.
        /// </summary>
        public static string DeleteRenter {
            get {
                return ResourceManager.GetString("DeleteRenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket/{0}.
        /// </summary>
        public static string DeleteTicket {
            get {
                return ResourceManager.GetString("DeleteTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/{0}.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker/{0}.
        /// </summary>
        public static string DeleteWorker {
            get {
                return ResourceManager.GetString("DeleteWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration/{0}.
        /// </summary>
        public static string GetAdministration {
            get {
                return ResourceManager.GetString("GetAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account/.
        /// </summary>
        public static string GetAllAccounts {
            get {
                return ResourceManager.GetString("GetAllAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration/.
        /// </summary>
        public static string GetAllAdministrations {
            get {
                return ResourceManager.GetString("GetAllAdministrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista/.
        /// </summary>
        public static string GetAllChecklist {
            get {
                return ResourceManager.GetString("GetAllChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/.
        /// </summary>
        public static string GetAllCities {
            get {
                return ResourceManager.GetString("GetAllCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonData/.
        /// </summary>
        public static string GetAllCommonData {
            get {
                return ResourceManager.GetString("GetAllCommonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonDataItem/.
        /// </summary>
        public static string GetAllCommonDataItems {
            get {
                return ResourceManager.GetString("GetAllCommonDataItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consorcio/.
        /// </summary>
        public static string GetAllConsortium {
            get {
                return ResourceManager.GetString("GetAllConsortium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsortiumSecure/.
        /// </summary>
        public static string GetAllConsortiumSecure {
            get {
                return ResourceManager.GetString("GetAllConsortiumSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad/.
        /// </summary>
        public static string GetAllFunctionalUnits {
            get {
                return ResourceManager.GetString("GetAllFunctionalUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items/.
        /// </summary>
        public static string GetAllItems {
            get {
                return ResourceManager.GetString("GetAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaboralUnion/.
        /// </summary>
        public static string GetAllLaboralUnion {
            get {
                return ResourceManager.GetString("GetAllLaboralUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager/.
        /// </summary>
        public static string GetAllManagers {
            get {
                return ResourceManager.GetString("GetAllManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message/.
        /// </summary>
        public static string GetAllMessages {
            get {
                return ResourceManager.GetString("GetAllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner/.
        /// </summary>
        public static string GetAllOwners {
            get {
                return ResourceManager.GetString("GetAllOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedad/All.
        /// </summary>
        public static string GetAllOwnerships {
            get {
                return ResourceManager.GetString("GetAllOwnerships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentType/.
        /// </summary>
        public static string GetAllPaymentTypes {
            get {
                return ResourceManager.GetString("GetAllPaymentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority/.
        /// </summary>
        public static string GetAllPriorities {
            get {
                return ResourceManager.GetString("GetAllPriorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider/.
        /// </summary>
        public static string GetAllProviders {
            get {
                return ResourceManager.GetString("GetAllProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province/.
        /// </summary>
        public static string GetAllProvinces {
            get {
                return ResourceManager.GetString("GetAllProvinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renter/.
        /// </summary>
        public static string GetAllRenter {
            get {
                return ResourceManager.GetString("GetAllRenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureStatus/.
        /// </summary>
        public static string GetAllSecureStatus {
            get {
                return ResourceManager.GetString("GetAllSecureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status/.
        /// </summary>
        public static string GetAllStatus {
            get {
                return ResourceManager.GetString("GetAllStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskResult/.
        /// </summary>
        public static string GetAllTaskResult {
            get {
                return ResourceManager.GetString("GetAllTaskResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets/.
        /// </summary>
        public static string GetAllTicket {
            get {
                return ResourceManager.GetString("GetAllTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users/.
        /// </summary>
        public static string GetAllUsers {
            get {
                return ResourceManager.GetString("GetAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker/.
        /// </summary>
        public static string GetAllWorkers {
            get {
                return ResourceManager.GetString("GetAllWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consorcio/{0}/Tickets.
        /// </summary>
        public static string GetByConsortiumId {
            get {
                return ResourceManager.GetString("GetByConsortiumId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista/{0}.
        /// </summary>
        public static string GetChecklist {
            get {
                return ResourceManager.GetString("GetChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consorcio/{0}/Checklists.
        /// </summary>
        public static string GetChecklistsByConsortium {
            get {
                return ResourceManager.GetString("GetChecklistsByConsortium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonData/{0}.
        /// </summary>
        public static string GetCommonData {
            get {
                return ResourceManager.GetString("GetCommonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consorcio/{0}.
        /// </summary>
        public static string GetConsortium {
            get {
                return ResourceManager.GetString("GetConsortium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsortiumSecure/{0}.
        /// </summary>
        public static string GetConsortiumSecure {
            get {
                return ResourceManager.GetString("GetConsortiumSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad/{0}.
        /// </summary>
        public static string GetFunctionalUnit {
            get {
                return ResourceManager.GetString("GetFunctionalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager/{0}.
        /// </summary>
        public static string GetManager {
            get {
                return ResourceManager.GetString("GetManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message/{0}.
        /// </summary>
        public static string GetMessage {
            get {
                return ResourceManager.GetString("GetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia/{0}.
        /// </summary>
        public static string GetMultimedia {
            get {
                return ResourceManager.GetString("GetMultimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner/{0}.
        /// </summary>
        public static string GetOwner {
            get {
                return ResourceManager.GetString("GetOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedad/{0}.
        /// </summary>
        public static string GetOwnership {
            get {
                return ResourceManager.GetString("GetOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider/{0}.
        /// </summary>
        public static string GetProvider {
            get {
                return ResourceManager.GetString("GetProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country/{0}/Provinces.
        /// </summary>
        public static string GetProvincesByCountry {
            get {
                return ResourceManager.GetString("GetProvincesByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renter/{0}.
        /// </summary>
        public static string GetRenter {
            get {
                return ResourceManager.GetString("GetRenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets/{0}.
        /// </summary>
        public static string GetTicket {
            get {
                return ResourceManager.GetString("GetTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedad/{0}/Unidades.
        /// </summary>
        public static string GetUnits {
            get {
                return ResourceManager.GetString("GetUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users/{0}.
        /// </summary>
        public static string GetUser {
            get {
                return ResourceManager.GetString("GetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker/{0}.
        /// </summary>
        public static string GetWorker {
            get {
                return ResourceManager.GetString("GetWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account/Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration/{0}.
        /// </summary>
        public static string UpdateAdministration {
            get {
                return ResourceManager.GetString("UpdateAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista/{0}.
        /// </summary>
        public static string UpdateChecklist {
            get {
                return ResourceManager.GetString("UpdateChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonData/{0}.
        /// </summary>
        public static string UpdateCommonData {
            get {
                return ResourceManager.GetString("UpdateCommonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consortium/{0}.
        /// </summary>
        public static string UpdateConsortium {
            get {
                return ResourceManager.GetString("UpdateConsortium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsortiumSecure/{0}.
        /// </summary>
        public static string UpdateConsortiumSecure {
            get {
                return ResourceManager.GetString("UpdateConsortiumSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit/{0}.
        /// </summary>
        public static string UpdateFunctionalUnit {
            get {
                return ResourceManager.GetString("UpdateFunctionalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager/{0}.
        /// </summary>
        public static string UpdateManager {
            get {
                return ResourceManager.GetString("UpdateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner/{0}.
        /// </summary>
        public static string UpdateOwner {
            get {
                return ResourceManager.GetString("UpdateOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedad/{0}.
        /// </summary>
        public static string UpdateOwnership {
            get {
                return ResourceManager.GetString("UpdateOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider/{0}.
        /// </summary>
        public static string UpdateProvider {
            get {
                return ResourceManager.GetString("UpdateProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renter/{0}.
        /// </summary>
        public static string UpdateRenter {
            get {
                return ResourceManager.GetString("UpdateRenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket/{0}.
        /// </summary>
        public static string UpdateTicket {
            get {
                return ResourceManager.GetString("UpdateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/{0}.
        /// </summary>
        public static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker/{0}.
        /// </summary>
        public static string UpdateWorker {
            get {
                return ResourceManager.GetString("UpdateWorker", resourceCulture);
            }
        }
    }
}
