//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Library.ApiResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiCore {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiCore() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Administracion.Library.ApiResources.ApiCore", typeof(ApiCore).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consortium/.
        /// </summary>
        public static string CreateConsortium {
            get {
                return ResourceManager.GetString("CreateConsortium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tickets/.
        /// </summary>
        public static string CreateTicket {
            get {
                return ResourceManager.GetString("CreateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User/.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consortium/.
        /// </summary>
        public static string DeleteConsortium {
            get {
                return ResourceManager.GetString("DeleteConsortium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tickets/.
        /// </summary>
        public static string DeleteTicket {
            get {
                return ResourceManager.GetString("DeleteTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User/.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consortium/.
        /// </summary>
        public static string GetConsortium {
            get {
                return ResourceManager.GetString("GetConsortium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tickets/.
        /// </summary>
        public static string GetTicket {
            get {
                return ResourceManager.GetString("GetTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User/.
        /// </summary>
        public static string GetUser {
            get {
                return ResourceManager.GetString("GetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account/Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consortium/.
        /// </summary>
        public static string UpdateConsortium {
            get {
                return ResourceManager.GetString("UpdateConsortium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tickets/.
        /// </summary>
        public static string UpdateTicket {
            get {
                return ResourceManager.GetString("UpdateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User/.
        /// </summary>
        public static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
    }
}
