//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCore.Library.Mensajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApiCore.Library.Mensajes.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El abono indicado no existe para el anunciate.
        /// </summary>
        public static string AbonoNoPerteneceAlAnunciante {
            get {
                return ResourceManager.GetString("AbonoNoPerteneceAlAnunciante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso denegado. Su usuario no tiene permisos para la acción..
        /// </summary>
        public static string AccesoDenegado {
            get {
                return ResourceManager.GetString("AccesoDenegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Anunciante no existe..
        /// </summary>
        public static string AnuncianteNoEncontrado {
            get {
                return ResourceManager.GetString("AnuncianteNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Anunciante no tiene abonos con esas caracteristicas..
        /// </summary>
        public static string AnuncianteSinAbonosDeEsaCaracteristica {
            get {
                return ResourceManager.GetString("AnuncianteSinAbonosDeEsaCaracteristica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El aviso no existe o fue eliminado..
        /// </summary>
        public static string AvisoInexistenteOEliminado {
            get {
                return ResourceManager.GetString("AvisoInexistenteOEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la llamada..
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Banner no existe..
        /// </summary>
        public static string BannerNoExiste {
            get {
                return ResourceManager.GetString("BannerNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Cliente no Existe.
        /// </summary>
        public static string ClienteNoExiste {
            get {
                return ResourceManager.GetString("ClienteNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encunetra un anunciante sap asociado al idAnunciante {0}.
        /// </summary>
        public static string EquivalenciaAnuncianteSapError {
            get {
                return ResourceManager.GetString("EquivalenciaAnuncianteSapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene acceso..
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en el servidor, vuelva a intentarlo..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra el recurso..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se Indico un Pack que no existe..
        /// </summary>
        public static string PackInvalido {
            get {
                return ResourceManager.GetString("PackInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Path no existe o es invalido..
        /// </summary>
        public static string PathInvalido {
            get {
                return ResourceManager.GetString("PathInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No posee suficientes puntos para modificar el aviso; comuniquese con su ejecutivo de cuentas..
        /// </summary>
        public static string PuntosInsuficientes {
            get {
                return ResourceManager.GetString("PuntosInsuficientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al acceder a redis master. {0}.
        /// </summary>
        public static string RedisMasterError {
            get {
                return ResourceManager.GetString("RedisMasterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El SAP Cliente ingresado ya ha sido utilizado..
        /// </summary>
        public static string SapClienteExiste {
            get {
                return ResourceManager.GetString("SapClienteExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Anunciante no tiene Cliente asociado..
        /// </summary>
        public static string SinCliente {
            get {
                return ResourceManager.GetString("SinCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se necesita asignar un ejecutivo de venta..
        /// </summary>
        public static string SinEjecutivoVenta {
            get {
                return ResourceManager.GetString("SinEjecutivoVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token inválido. Vuelva a loguearse..
        /// </summary>
        public static string TokenInvalido {
            get {
                return ResourceManager.GetString("TokenInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token no enviado. Debe enviar su token con la petición..
        /// </summary>
        public static string TokenNoEnviado {
            get {
                return ResourceManager.GetString("TokenNoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario/Password no válido..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El UserName ya existe..
        /// </summary>
        public static string UsuarioExistente {
            get {
                return ResourceManager.GetString("UsuarioExistente", resourceCulture);
            }
        }
    }
}
